// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/vnnyx/golang-dot-api/controller/auth"
	transaction2 "github.com/vnnyx/golang-dot-api/controller/transaction"
	"github.com/vnnyx/golang-dot-api/controller/user"
	"github.com/vnnyx/golang-dot-api/infrastructure"
	"github.com/vnnyx/golang-dot-api/middleware"
	auth2 "github.com/vnnyx/golang-dot-api/repository/auth"
	"github.com/vnnyx/golang-dot-api/repository/transaction"
	user2 "github.com/vnnyx/golang-dot-api/repository/user"
	auth3 "github.com/vnnyx/golang-dot-api/service/auth"
	transaction3 "github.com/vnnyx/golang-dot-api/service/transaction"
	user3 "github.com/vnnyx/golang-dot-api/service/user"
)

// Injectors from wire.go:

func InitializeUserController(configName string) user.UserController {
	config := infrastructure.NewConfig(configName)
	db := infrastructure.NewMySQLDatabase(config)
	userRepository := user2.NewUserRepository(db)
	transactionRepository := transaction.NewTransactionRepository(db)
	userService := user3.NewUserService(userRepository, transactionRepository, db)
	authMiddleware := middleware.NewAuthMiddleware(configName)
	userController := user.NewUserController(userService, authMiddleware)
	return userController
}

func InitializeTransactionController(configName string) transaction2.TransactionController {
	config := infrastructure.NewConfig(configName)
	db := infrastructure.NewMySQLDatabase(config)
	transactionRepository := transaction.NewTransactionRepository(db)
	userRepository := user2.NewUserRepository(db)
	transactionService := transaction3.NewTransactionService(transactionRepository, userRepository)
	authMiddleware := middleware.NewAuthMiddleware(configName)
	transactionController := transaction2.NewTransactionController(transactionService, authMiddleware)
	return transactionController
}

func InitializeAuthController(configName string) auth.AuthController {
	config := infrastructure.NewConfig(configName)
	db := infrastructure.NewMySQLDatabase(config)
	userRepository := user2.NewUserRepository(db)
	client := infrastructure.NewRedisClient(configName)
	authRepository := auth2.NewAuthRepository(client)
	authService := auth3.NewAuthService(config, db, userRepository, authRepository)
	authMiddleware := middleware.NewAuthMiddleware(configName)
	authController := auth.NewAuthController(authService, authMiddleware)
	return authController
}
