version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.tests
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - integration-test

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dot_test_database
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - integration-test

  redis:
    image: redis:alpine
    restart: always
    networks:
      - integration-test

networks:
  integration-test:
    driver: bridge