version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.tests
    restart: on-failure
    networks:
      - dot_net
networks:
  dot_net:
    name: root_dot
    external: true