name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Download Dependency
      run: go mod tidy

    - name: Test
      run: cd test/unit && make test

    - name: Build
      run: go build -v ./...